ALTER TABLE "Click"
ADD COLUMN "referrer" TEXT,
ADD COLUMN "utmSource" TEXT,
ADD COLUMN "utmMedium" TEXT,
ADD COLUMN "utmCampaign" TEXT,
ADD COLUMN "utmTerm" TEXT,
ADD COLUMN "utmContent" TEXT,
ADD COLUMN "source" TEXT,
ADD COLUMN "deviceType" TEXT,
ADD COLUMN "browser" TEXT,
ADD COLUMN "operatingSystem" TEXT,
ADD COLUMN "platform" TEXT,
ADD COLUMN "language" TEXT,
ADD COLUMN "geoCountry" TEXT,
ADD COLUMN "geoRegion" TEXT,
ADD COLUMN "geoCity" TEXT,
ADD COLUMN "timezone" TEXT,
ADD COLUMN "screenWidth" INTEGER,
ADD COLUMN "screenHeight" INTEGER;

ALTER TABLE "Conversion"
ADD COLUMN "referrer" TEXT,
ADD COLUMN "utmSource" TEXT,
ADD COLUMN "utmMedium" TEXT,
ADD COLUMN "utmCampaign" TEXT,
ADD COLUMN "utmTerm" TEXT,
ADD COLUMN "utmContent" TEXT,
ADD COLUMN "deviceType" TEXT,
ADD COLUMN "browser" TEXT,
ADD COLUMN "operatingSystem" TEXT,
ADD COLUMN "platform" TEXT,
ADD COLUMN "language" TEXT,
ADD COLUMN "geoCountry" TEXT,
ADD COLUMN "geoRegion" TEXT,
ADD COLUMN "geoCity" TEXT,
ADD COLUMN "timezone" TEXT,
ADD COLUMN "screenWidth" INTEGER,
ADD COLUMN "screenHeight" INTEGER;
